#!/bin/bash

bindir=$( (cd -P $(dirname $0) && pwd) )
dir=$( (cd -P $(dirname $0)/.. && pwd) )
tmpdir=$( (cd -P $dir/tmp && pwd) )

solrURL=http://libsvr40.lib.virginia.edu:8983/solr/bib

barcode=$1
abstract=$2
advisorxmlfile=$3
language=$4
note="Digitization of this thesis was made possible by a generous grant from the Jefferson Trust, 2015."

tmpfile=$tmpdir/${barcode}_index_out.txt

$bindir/getfromsolr "$solrURL" barcode_facet:"$barcode" | $bindir/indextest jeffersontrust.properties | tee "$tmpfile" |
    sed -e 's/u[0-9]* : //' -e 's/ = /@/' | $bindir/getmodsfrommarc "$barcode" "$abstract" "$advisorxmlfile" "$language" "$note"  2> /dev/null 

